name: Testing Suite # name of the test

# the Github Action will activate "on" the event that you "make a pr" to main
on:
  pull_request:
    branches:
      - main

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
    
      - name: Install Dependencies
        working-directory: ./source
        run: npm install
        
      - name: Unit Test
        working-directory: ./source
        run: npm run test